-- Tabla Libros
CREATE TABLE IF NOT EXISTS Libro (
    CODLIBRO DECIMAL(4,0) PRIMARY KEY,
    TITULO VARCHAR(100) NOT NULL,
    CODAUTOR DECIMAL(4,0),
    CODCATEGORIA DECIMAL(4,0),
    PRECIO DECIMAL(10, 2),
    FOREIGN KEY (CODAUTOR) REFERENCES Autor(CODAUTOR),
    FOREIGN KEY (CODCATEGORIA) REFERENCES Categoria(CODCATEGORIA)
);

-- Tabla Clientes
CREATE TABLE IF NOT EXISTS Cliente (
    CODCLIENTE DECIMAL(4,0) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    TELEFONO VARCHAR(20)
);

-- Tabla Pedidos
CREATE TABLE IF NOT EXISTS Pedido (
    CODPEDIDO DECIMAL(4,0) PRIMARY KEY,
    CODCLIENTE DECIMAL(4,0),
    FECHA DATE,
    FOREIGN KEY (CODCLIENTE) REFERENCES Cliente(CODCLIENTE)
);

-- Tabla Autores
CREATE TABLE IF NOT EXISTS Autor (
    CODAUTOR DECIMAL(4,0) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDOS VARCHAR(50)
);

-- Tabla Categorias
CREATE TABLE IF NOT EXISTS Categoria (
    CODCATEGORIA DECIMAL(4,0) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(100)
);